// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8WSfkvZ9nZ_7bb95QqFPMr9TTpjZMYqs',
    appId: '1:83370450098:web:37e4b9e557378329827dab',
    messagingSenderId: '83370450098',
    projectId: 'flutree-a512b',
    authDomain: 'flutree-a512b.firebaseapp.com',
    storageBucket: 'flutree-a512b.firebasestorage.app',
    measurementId: 'G-CQ5DMFLNP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD51Xx9iwsJWHUq63D5ndmOYdpXVJvhLm8',
    appId: '1:83370450098:android:abe7b303cd088a48827dab',
    messagingSenderId: '83370450098',
    projectId: 'flutree-a512b',
    storageBucket: 'flutree-a512b.firebasestorage.app',
    androidClientId: '83370450098-rcupejuo2qe8gov1vfif3kes7phkdjs1.apps.googleusercontent.com',
  );

  // iOS Firebase configuration
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_u0qt0lZS6sOH6reRRQdtrd8QvcfYJlY',
    appId: '1:83370450098:ios:b83e7f01b6f2abbe827dab',
    messagingSenderId: '83370450098',
    projectId: 'flutree-a512b',
    storageBucket: 'flutree-a512b.firebasestorage.app',
    iosClientId: '83370450098-2eqd7sumdhtp1q7jmu8qsnjqe5jscfc9.apps.googleusercontent.com',
    iosBundleId: 'com.vlagit.vlag',
  );
}
